
name: Tutorial

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name:  Step 1 for Tutorial
      run: |
        echo "Echo Basic Information"
        echo "#Ref: $GITHUB_REF"
        echo "Job ID: $GITHUB_JOB"
        echo "Action: $GITHUB_ACTION"
        echo "Job ID: $GITHUB_ACTION"
